### ISSUE TITLE
你们的仓库下的目录结构多了一层？

### ISSUE THREAD

**Issue by GTZhou** [clkgtr5/JavaProTest#2]
请参考其他组的目录结构。

**Comment by clkgtr5** [comment]
老师你是指cn.com.tatena这个包吗？取名的时候取错了。

**Comment by GTZhou** [comment]
不是，你们的这个仓库_JavaProTest https://github.com/clkgtr5/JavaProTest_
下应该直接是src,web这些目录，现在又多出了一层Gwap这样的目录。

在 2015年1月14日 下午10:09，clkgtr5 notifications@github.com写道：

**Comment by clkgtr5** [comment]
这样啊，不知道怎么改仓库目录。我试试看。

**Comment by clkgtr5** [comment]
我把本地的项目的目录文件夹结构修改了重新上传了项目。网上仓库的目录结构修改了。

**Comment by GTZhou** [comment]
OK，现在正确了！
